name: TG Bot
on:
  workflow_dispatch:
  push:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: 安装依赖
        run: pip install pytelegrambotapi
      - name: 启动机器人
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python main.py

        
